name: Snake Game

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoder1/github-readme-streak-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          snake: github-snake-game.svg
          mode: github-snake-game
